export const SET_DASHBOARD_LOADING = "SET_DASHBOARD_LOADING";

export const DASHBOARD_DATA_SUCCESS = "DASHBOARD_DATA_SUCCESS";
export const DASHBOARD_DATA_FAIL = "DASHBOARD_DATA_FAIL";
export const DASHBOARD_FILTER_SUCCESS = "DASHBOARD_FILTER_SUCCESS";
export const DASHBOARD_FILTER_FAIL = "DASHBOARD_FILTER_FAIL";
